---
- hosts: lt_nodes
  tasks:
    - name: apt update
      command: apt update
      become: yes

    - name: install pip3
      command: apt install python3-pip -y
      become: yes

    - name: install confluent kafka
      command: pip3 install confluent-kafka
      become: yes

    - name: install fastavro
      command: pip3 install fastavro
      become: yes

    - name: install mysql.connector
      command: pip3 install mysql-connector-python
      become: yes

      #    - name: install swift client
      #      command: pip3 install python-swiftclient
      #      become: yes

    - name: make local data directory
      file:
        path: /data/stamps/
        state: directory
        owner: ubuntu
      become: yes
