---
- hosts: lt_nodes:lt_archive
  tasks:
    - name: apt update
      command: apt update
      become: yes

    - name: install pip3
      command: apt install python3-pip -y
      become: yes

    - name: make scratch directory
      command: mkdir /home/ubuntu/scratch

    - name: make log directory
      command: mkdir /home/ubuntu/logs
