---
- hosts: lt_nodes:lt_archive

  tasks:
          - name: 'install mysql'
            command: 'apt install mysql-server -y'
            become: yes

          - name: 'permissions on mysql-files'
            command: 'chmod 777 /var/lib/mysql-files'
            become: yes

          - name: 'fetch code from github'
            command: 'cd LasairTech'
            register: result
            ignore_errors: True
          - command: 'git clone https://github.com/RoyWilliams/LasairTech.git'
            when: result is failed
          - command: 'git pull'
            args:
                    chdir: 'LasairTech'
            when: result is succeeded
                    
          - name: 'allow remote connections'
            command: 'sh allow_remote.sh'
            args:
                    chdir: 'LasairTech/database_tests/ansible/'
            become: yes

          - name: 'setup mysql'
            command: 'mysql < mysql_setup.sql'
            become: yes
            args:
                    chdir: 'LasairTech/database_tests/ansible/'
