---
- hosts: lt_nodes:lt_archive
  tasks:
   - name: pull from git
     git:
       repo: https://github.com/RoyWilliams/LasairTech.git
       dest: /home/ubuntu/LasairTech
       update: yes
       version: master

   - name: install mysql
     command: apt install mysql-server -y
     become: yes

   - name: Start the MySQL service
     action: service name=mysql state=started

   - name: permissions on mysql-files
     command: chmod 777 /var/lib/mysql-files
     become: yes

   - name: Copy my.cnf
     copy:
       src: /home/ubuntu/LasairTech/database_tests/ansible/my.cnf
       dest: /home/ubuntu/.my.cnf

   - name: allow remote connections
     command: sh allow_remote.sh
     args:
       chdir: LasairTech/database_tests/ansible/
     become: yes

   - name: setup mysql
     command: mysql < /home/ubuntu/LasairTech/database_tests/ansible/mysql_setup.sql
     become: yes
